language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_7dbe1e2dc648_key -iv $encrypted_7dbe1e2dc648_iv -in .travis/travis-gh.enc -out .travis/travis-gh -d
  - eval "$(ssh-agent -s)" && chmod 0600 .travis/travis-gh && ssh-add .travis/travis-gh && rm .travis/travis-gh
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/au/id/fsat
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
branches:
  only:
  - master
script:
  #- sbt clean test
  - sh release.sh
